//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SatCon.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SATCON_FORM                 101
#define IDD_SATCON_READ_FORM            101
#define IDD_SATCON_WRITE_FORM           102
#define IDR_SATCONWRITEVIEW_TMPL        103
#define IDD_BITSHOW_DIALOGBAR           103
#define IDD_SATCON_BITSHOW_FORM         104
#define IDR_SATCONBITSHOWVIEW_TMPL      105
#define ID_POPMENU_DELETE_ITEM          106
#define ID_SUBDLG_TOOLTIP               107
#define ID_POPMENU_NEW_ITEM             108
#define ID_POPMENU_NEW_PAGE             109
#define ID_POPMENU_DELETE_PAGE          110
#define ID_SUBWRITEDLG_TOOLTIP          111
#define IDD_MYCHART_FORM                113
#define IDR_MYCHART_TMPL                114
#define ID_CHART_DIALOG                 115
#define ID_OCHART_DIALOG                116
#define IDD_CALENDAR_DIALOG             117
#define IDD_MYCALENDAR_DIALOG           118
#define IDC_MONTHSELECT                 119
#define IDC_YEAREDIT                    120
#define IDC_BUTTODAY                    121
#define IDC_YEARSELECT                  122
#define IDR_MAINFRAME                   128
#define IDR_SATCONTYPE                  129
#define IDD_SUB_DIALOG                  130
#define IDD_SETPARA_DIALOG              131
#define IDD_VARNAME_SET_DIALOG          132
#define IDD_SUB_DIALOG_WRITE            133
#define IDD_SUB_DIALOG_BIT              134
#define IDD_BIT_SET_DIALOG              135
#define IDD_COMMSET_DIALOG              137
#define IDD_BUTTON_DIALOGBAR            138
#define IDI_ARROW_ICON                  142
#define IDI_ROOM_ICON                   143
#define IDI_TRIGON_ICON                 144
#define IDI_STOP_ICON                   145
#define IDB_BITMAP1                     146
#define IDB_BITMAP2                     149
#define IDB_SHUTDOWN_BITMAP             149
#define IDB_STOP_BITMAP                 150
#define IDB_START_BITMAP                151
#define IDB_RESET_BITMAP                152
#define IDD_PASSWORD_DIALOG             153
#define IDD_DIALOG                      156
#define IDD_TOPBITSET_DIALOG            156
#define IDD_DIALOG1                     157
#define IDD_TOPREADSET_DIALOG           157
#define IDD_DIALOGBAR_BIT               159
#define IDD_DIALOGBAR_RW                160
#define IDD_SEL_DIRECTORY_DIALOG        161
#define IDD_OLDCHART_DIALOG             162
#define IDD_CALENDAR_SHOW               163
#define IDC_BITSHOW_TAB                 1000
#define IDC_WRITE_TAB                   1001
#define IDC_READ_TAB                    1003
#define IDC_READER_TAB                  1003
#define IDC_READ_VAL_EDIT               1005
#define IDC_READ_UNIT_EDIT              1006
#define IDC_READ_BASE_GROUP             1007
#define IDC_NAME_COMBO                  1008
#define IDC_VALUE_EDIT                  1009
#define IDC_ADDERSS_EDIT                1010
#define IDC_STEP_EDIT                   1011
#define IDC_MIN_EDIT                    1012
#define IDC_COMMENT_EDIT                1013
#define IDC_CHECK1                      1014
#define IDC_WABLE_CHECK                 1014
#define IDC_CHECK2                      1015
#define IDC_RABLE_CHECK                 1015
#define IDC_CHECK3                      1016
#define IDC_RCONT_CHECK                 1016
#define IDC_DECADAL_EDIT                1017
#define IDC_BINARY_EDIT                 1018
#define IDC_FORMAT_EDIT                 1019
#define IDC_RESET_BUTTON                1021
#define IDC_VARNAME_COMBO               1021
#define IDC_UNIT_EDIT                   1023
#define IDC_TABNAME_EDIT                1023
#define IDC_MAX_EDIT                    1024
#define IDC_EDIT1                       1024
#define IDC_WRITE_VRL_EDIT              1024
#define IDC_DISPLAY0_EDIT               1024
#define IDC_PASSWORD_EDIT               1024
#define IDC_EDIT2                       1025
#define IDC_WRITE_CURRVAL_EDIT          1025
#define IDC_DISPLAY1_EDIT               1025
#define IDC_EDIT3                       1026
#define IDC_WRITE_UNIT_EDIT             1026
#define IDC_BITCOM_EDIT                 1026
#define IDC_EDIT4                       1027
#define IDC_WRITE_STEP_EDIT             1027
#define IDC_OK_BUTTON                   1028
#define IDC_EDIT5                       1028
#define IDC_SAVE_BUTTON                 1029
#define IDC_EDIT6                       1029
#define IDC_ADD_BUTTON                  1030
#define IDC_EDIT7                       1030
#define IDC_DEC_BUTTON                  1031
#define IDC_EDIT8                       1031
#define IDC_WRITE_GROUP                 1032
#define IDC_EDIT9                       1032
#define IDC_EDIT10                      1033
#define IDC_BITNO_COMBO                 1034
#define IDC_SELCOLOR0_STATIC            1035
#define IDC_SETBIT_STATIC               1036
#define IDC_ITEMNUM_STATIC              1036
#define IDC_SELCOLOR1_STATIC            1037
#define IDC_PORT_COMBO                  1038
#define IDC_BAUD_COMBO                  1039
#define IDC_BUTTON1                     1039
#define IDC_SHUTDOWN_BUTTON             1039
#define IDC_LED_BUTTON                  1039
#define IDC_SAVEALL_BUTTON              1039
#define IDC_BROWSE_BUTTON               1039
#define IDC_OLDCHART_BUTTON             1039
#define IDC_PARITY_COMBO                1040
#define IDC_BUTTON2                     1040
#define IDC_LOADFPC_BUTTON              1040
#define IDC_DATA_COMBO                  1041
#define IDC_BUTTON3                     1041
#define IDC_START_BUTTON                1041
#define IDC_LOADFDSP_BUTTON             1041
#define IDC_STOP_COMBO                  1042
#define IDC_STOP_BUTTON                 1042
#define IDC_CLEAR_BUTTON                1042
#define IDC_PASSWORD_STATIC             1043
#define IDC_PROMPT_STATIC               1044
#define IDC_BITNAME_STATIC              1045
#define IDC_EDIT11                      1046
#define IDC_EDIT12                      1047
#define IDC_VARIABLE_COMBO              1047
#define IDC_EDIT13                      1048
#define IDC_BIT_COMBO                   1048
#define IDC_EDIT14                      1049
#define IDC_COLOR_STATIC                1049
#define IDC_EDIT15                      1050
#define IDC_MSCOMM                      1050
#define IDC_EDIT16                      1051
#define IDC_BIT_STATIC1                 1052
#define IDC_BIT_STATIC2                 1053
#define IDC_BIT_STATIC3                 1054
#define IDC_BIT_STATIC4                 1055
#define IDC_BIT_STATIC5                 1056
#define IDC_BIT_STATIC6                 1057
#define IDC_BIT_STATIC7                 1058
#define IDC_BIT_STATIC8                 1059
#define IDC_BIT_STATIC9                 1060
#define IDC_BIT_STATIC10                1061
#define IDC_NAME_STATIC1                1062
#define IDC_NAME_STATIC2                1063
#define IDC_NAME_STATIC3                1064
#define IDC_BIT_STATIC                  1064
#define IDC_VALNAMEBAR_STATIC           1065
#define IDC_UNITBAR_STATIC              1066
#define IDC_VALBAR_STATIC               1066
#define IDC_NAME_STATIC6                1067
#define IDC_DIRECTORY_COMBO             1067
#define IDC_NAME_STATIC7                1068
#define IDC_ERROR_STATIC                1068
#define IDC_VALUE_STATIC1               1069
#define IDC_TITLE_STATIC                1069
#define IDC_VALUE_STATIC2               1070
#define IDC_VALUE_STATIC3               1071
#define IDC_VALUE_STATIC4               1072
#define IDC_COMBO_PARA                  1072
#define IDC_VALUE_STATIC5               1073
#define IDC_MONTHCALENDAR               1073
#define IDC_VALUE_STATIC6               1074
#define IDC_VALUE_STATIC7               1075
#define IDC_BASE_BUTTON                 2000
#define ID_MENU_OPR_SHUT                32771
#define ID_MENU_OPR_RESET               32772
#define ID_MENU_OPR_START               32773
#define ID_MENU_OPR_STOP                32774
#define ID_MENU_OPR_CNTPCS              32775
#define ID_MENU_OPR_DISCNTPCS           32776
#define ID_MENU_OPR_CNNSET              32777
#define ID_MENU_OPR_USERLEVEL           32778
#define ID_MENU_OPR_SERCERLEVEL         32779
#define ID_MENU_OPR_SYSLEVEL            32780
#define ID_MENU_BITSHOW                 32782
#define ID_MENU_WRITER                  32783
#define ID_MENU_READER                  32784
#define ID_MENU_SET_PARAMETERS          32785
#define ID_MENU_UPLOAD_DSP_PC           32786
#define ID_MENU_DOWNLOAD_PC_DSP         32787
#define ID_STATE_INFO                   61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
